-- Intial load for date_dim using DWEEK, DMONTH, DQUARTERJL

INSERT OVERWRITE INTO jlp_bps.initial_schema.date_dim
SELECT DISTINCT DWEEK, DMONTH, DQUARTERJL
FROM JLP_TABLE_PKS
ORDER BY DWEEK, DMONTH, DQUARTERJL
;