INSERT OVERWRITE INTO jlp_bps.initial_schema.dwave_rotation
SELECT DISTINCT DWAVE, DWEEK, DMONTH, DQUARTERJL, DSPLITSECTION_1, dsplitsection_2, DSPLITSECTION_3, DSPLITSECTION_4, dsplitsection_5, dsplitsection_6
FROM JLP_TABLE_PKS
ORDER BY DWEEK, DMONTH, DQUARTERJL
;